[package]
name = "tmi_chat"
version = "0.1.0"
authors = ["stevan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.11.1"
url = "2.1.1"
http = "0.2.1"
